;Fins administrativos. Esta função é bem custosa, então não a use a menos que saiba o que está fazendo!

(defn- reload-banco []
 "Uma funcao para restaurar o banco de dados, e fazer eventuais alterações que envolvam todos os arquivos .xml"
 	(destroi-tabelas)
 	(criar-tabela-exercicio)
; 	(criar-tabela-multimidia)
; 	(criar-tabela-apresentacao)
	(inserir-exercicio "v001" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v001.xml"))
	(inserir-exercicio "v002" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v002.xml"))
	(inserir-exercicio "v003" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v003.xml"))
	(inserir-exercicio "v004" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v004.xml"))
	(inserir-exercicio "v005" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v005.xml"))
	(inserir-exercicio "v006" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v006.xml"))
	(inserir-exercicio "v007" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v007.xml"))
	(inserir-exercicio "v008" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v008.xml"))
	(inserir-exercicio "v009" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v009.xml"))
	(inserir-exercicio "v010" "vetor" "facil" "me" (slurp "src/dominio/vetor/exercicios/v010.xml"))
	(inserir-exercicio "v011" "vetor" "medio" "programacao" (slurp "src/dominio/vetor/exercicios/v011.xml"))
	(inserir-exercicio "v012" "vetor" "dificil" "programacao" (slurp "src/dominio/vetor/exercicios/v012.xml"))
	
	(inserir-exercicio "r001" "recursividade" "facil" "me" (slurp "src/dominio/recursiv/exercicios/r001.xml"))
	(inserir-exercicio "r002" "recursividade" "medio" "programacao" (slurp "src/dominio/recursiv/exercicios/r002.xml"))
	
	(inserir-exercicio "l001" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l001.xml"))
	(inserir-exercicio "l002" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l002.xml"))
	(inserir-exercicio "l003" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l003.xml"))
	(inserir-exercicio "l004" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l004.xml"))
	(inserir-exercicio "l005" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l005.xml"))
	(inserir-exercicio "l006" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l006.xml"))
	(inserir-exercicio "l007" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l007.xml"))
	(inserir-exercicio "l008" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l008.xml"))
	(inserir-exercicio "l009" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l009.xml"))
	(inserir-exercicio "l010" "lista" "facil" "me" (slurp "src/dominio/lista/exercicios/l010.xml"))
	(inserir-exercicio "l011" "lista" "medio" "programacao" (slurp "src/dominio/lista/exercicios/l011.xml"))
	(inserir-exercicio "l012" "lista" "medio" "programacao" (slurp "src/dominio/lista/exercicios/l012.xml"))
	(inserir-exercicio "l013" "lista" "facil" "programacao" (slurp "src/dominio/lista/exercicios/l013.xml"))
	(inserir-exercicio "l014" "lista" "dificil" "programacao" (slurp "src/dominio/lista/exercicios/l014.xml"))
	
	(inserir-exercicio "f001" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f001.xml"))
	(inserir-exercicio "f002" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f002.xml"))
	(inserir-exercicio "f003" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f003.xml"))
	(inserir-exercicio "f004" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f004.xml"))
	(inserir-exercicio "f005" "fila" "facil" "vf" (slurp "src/dominio/fila/exercicios/f005.xml"))
	(inserir-exercicio "f006" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f006.xml"))
	(inserir-exercicio "f007" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f007.xml"))
	(inserir-exercicio "f008" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f008.xml"))
	(inserir-exercicio "f009" "fila" "facil" "me" (slurp "src/dominio/fila/exercicios/f009.xml"))
	(inserir-exercicio "f010" "fila" "facil" "aa" (slurp "src/dominio/fila/exercicios/f010.xml"))
	
	(inserir-exercicio "ad001" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad001.xml"))
	(inserir-exercicio "ad002" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad002.xml"))
	(inserir-exercicio "ad003" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad003.xml"))
	(inserir-exercicio "ad004" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad004.xml"))
	(inserir-exercicio "ad005" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad005.xml"))
	(inserir-exercicio "ad006" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad006.xml"))
	(inserir-exercicio "ad007" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad007.xml"))
	(inserir-exercicio "ad008" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad008.xml"))
	(inserir-exercicio "ad009" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad009.xml"))
	(inserir-exercicio "ad010" "alocacao dinamica" "facil" "me" (slurp "src/dominio/alocDin/exercicios/ad010.xml"))
  ) 
