(defn resetar-banco []
  (use 'ils.models.estudante.corygil.estudante)
  (cria-tabela-aluno)
  (cria-tabela-dominio)
  (cria-tabela-exercicio)
  (insere-tabela-aluno "11021BSI242" "Pablo" "Henrique" "BSI" "pablohenrique@si.ufu.br" "pablo" "182")
  (povoar-tabelas "11021BSI242")
  (use 'ils.models.dominio.dominio)
  (criar-tabela-exercicio-dominio)
  (inserir-exercicios "v001" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v001.xml"))
  (inserir-exercicios "v002" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v002.xml"))
  (inserir-exercicios "v003" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v003.xml"))
  (inserir-exercicios "v004" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v004.xml"))
  (inserir-exercicios "v005" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v005.xml"))
  (inserir-exercicios "v006" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v006.xml"))
  (inserir-exercicios "v007" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v007.xml"))
  (inserir-exercicios "v008" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v008.xml"))
  (inserir-exercicios "v009" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v009.xml"))
  (inserir-exercicios "v010" "vetor" "facil" "me" (slurp "src/ils/models/dominio/vetor/exercicios/v010.xml"))
)